name: my-books
services:
  books:
    image: okteto.dev/books
    build: .
    public: true
    ports:
      - 8080
    environment:
      - POSTGRES_PASSWORD=password
      - POSTGRES_USER=user 
      - POSTGRES_DB=books
  db:
    image: postgres:13-alpine
    ports:
      - 5432
    environment:
      - POSTGRES_PASSWORD=password
      - POSTGRES_USER=user 
      - POSTGRES_DB=books 